platform :ios, '6.0'
pod 'MagicalRecord', '~> 2.1'
pod 'NSHash', '~> 1.0.1'
pod 'JASidePanels'
pod 'TBXML', '~> 1.5'
pod 'TestFlightSDK', '~> 1.2.3.beta1'
pod 'Facebook-iOS-SDK', '~> 3.2.0'
pod 'Parse', '~> 1.1.33'
